service: aws-lambda-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  profile: deploy-aws
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}

resources:
  Resources:
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: get
          path: /hello

  registerUser:
    handler: handlers/registerUser.registerUser
    events:
      - httpApi:
          method: post
          path: /registerUser

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  DB:
    prefix: "LearnFunctions" # WARNING: Not change the prefix, do it delete al DB documents
  
  serverless-offline:
    httpPort: 4000

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      seed: true
      migrate: true
      inMemory: false
      dbPath: ${env:PWD}/database

  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn
