QuizTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.DB.prefix}-QuizTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST

    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: userEmail
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: userEmail
        KeyType: RANGE
