QuizTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.DB.prefix}-QuizTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST

    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: userId
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: quiz-userId
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
