UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.DB.prefix}-UsersTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST

    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      # - AttributeName: secretId
      #   AttributeType: S
      - AttributeName: password
        AttributeType: S
      - AttributeName: email
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: users-password-email
        KeySchema:
          - AttributeName: password
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        Projection:
          ProjectionType: ALL